### ISSUE TITLE
Bug in Web.php at row 312

### ISSUE THREAD

**Issue by antoniogweb** [phpMussel/Web#3]
Hi,
in the file Web.php, at row 312, there is this code:

if (($Try = $this->ClientL10N->getString($Pull)) !== '') {

That gives this error when you try to upload a test virus (xxx is path to vendor folder):

"Fatal error: Uncaught Error: Call to a member function getString() on null in /xxxx/vendor/phpmussel/web/src/Web.php:312 Stack trace: #0"

I think you have forgotten the Loader, so maybe it should be (in this way it works):

if (($Try = $this->Loader->ClientL10N->getString($Pull)) !== '') {

**Comment by Maikuolan** [comment]
Whoops.. You're correct about that. Good catch. '^.^ Working on a fix now. :-)

**Comment by Maikuolan** [comment]
Fixed. :-)
